export interface Member {
  id: string;
  name: string;
  institution: string;
  zone: "norte" | "usach" | "ohiggins" | "centro" | "sur";
  category: "researcher" | "postgrad" | "technician" | "national_collab" | "intl_collab" | "board";
  role?: string; // used for board members only
  scholarUrl?: string;
  expertise?: string;
  bio?: string;
}

const S = (id: string) => `https://scholar.google.com/citations?user=${id}`;

export const MEMBERS: Member[] = [
  // Comité Directivo 2026
  { id: "board-marcela-calabi",  name: "Dra. Marcela Calabi-Floody", institution: "Universidad de La Frontera",       zone: "centro",   category: "board", role: "Coordinadora General",   scholarUrl: S("CmmbHmMAAAAJ") },
  { id: "board-leon-bravo",      name: "Dr. León A. Bravo",          institution: "Universidad de La Frontera",       zone: "centro",   category: "board", scholarUrl: S("_ERGBOEAAAAJ") },
  { id: "board-jenny-blamey",    name: "Dra. Jenny Blamey",          institution: "Universidad de Santiago de Chile", zone: "usach",    category: "board", scholarUrl: S("bXcdEp4AAAAJ") },
  { id: "board-gustavo-zuniga",  name: "Dr. Gustavo Zúñiga",         institution: "Universidad de Santiago de Chile", zone: "usach",    category: "board", scholarUrl: S("cLH8_BEAAAAJ") },
  { id: "board-pedro-zamorano",  name: "Dr. Pedro Zamorano",         institution: "Universidad de Antofagasta",       zone: "norte",    category: "board", scholarUrl: S("3fpYxmgAAAAJ") },
  { id: "board-mailing-rivera",  name: "Dra. Mailing Rivera",        institution: "Universidad de Antofagasta",       zone: "norte",    category: "board", scholarUrl: S("6jEQMNgAAAAJ") },
  { id: "board-alexander",       name: "Dr. Alexander Vergara",      institution: "Universidad de O'Higgins",         zone: "ohiggins", category: "board", scholarUrl: S("AQKvOdQAAAAJ") },
  { id: "board-manuel-martinez", name: "Dr. Manuel Martínez",        institution: "Universidad de O'Higgins",         zone: "ohiggins", category: "board", scholarUrl: S("LMTdtVYAAAAJ") },
  { id: "board-claudia-mansilla",name: "Dra. Claudia Mansilla",      institution: "Universidad de Magallanes",        zone: "sur",      category: "board", scholarUrl: S("8jkdO00AAAAJ") },

  // Universidad de Antofagasta — norte
  {
    id: "mailing-rivera",
    name: "Dra. Mailing Rivera",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    scholarUrl: S("6jEQMNgAAAAJ"),
  },
  {
    id: "pedro-zamorano",
    name: "Dr. Pedro Zamorano",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    scholarUrl: S("3fpYxmgAAAAJ"),
  },
  {
    id: "bernardita-valenzuela",
    name: "Bernardita Valenzuela Guerrero",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    expertise: "Microorganismos extremófilos",
  },
  {
    id: "mayra-cayo",
    name: "Mayra Cayo Torrejón",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    expertise: "Ecología de sistemas acuáticos",
  },
  {
    id: "pablo-aguilar",
    name: "Dr. Pablo Aguilar",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    scholarUrl: S("EQCRTIcAAAAJ"),
  },
  {
    id: "carolina-cubillos",
    name: "Dra. Carolina Cubillos",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    scholarUrl: S("uKr5ClsAAAAJ"),
  },
  {
    id: "raquel-rodriguez",
    name: "Dra. Raquel Rodríguez",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    scholarUrl: S("Up9xQO4AAAAJ"),
  },
  {
    id: "francisco-solis",
    name: "Francisco Solís",
    institution: "Universidad de Antofagasta",
    zone: "norte",
    category: "researcher",
    expertise: "Extremófilos",
  },

  // Universidad de Santiago de Chile — usach
  {
    id: "jenny-blamey",
    name: "Dra. Jenny Blamey",
    institution: "Universidad de Santiago de Chile",
    zone: "usach",
    category: "researcher",
    scholarUrl: S("bXcdEp4AAAAJ"),
    expertise: "Extremófilos, enzimas termoestables, Fundación Biociencia",
  },
  {
    id: "gustavo-zuniga",
    name: "Dr. Gustavo Zúñiga",
    institution: "Universidad de Santiago de Chile",
    zone: "usach",
    category: "researcher",
    scholarUrl: S("cLH8_BEAAAAJ"),
    expertise: "Biotecnología y fisiología vegetal, biología antártica",
  },
  { id: "claudia-ortiz",      name: "Dra. Claudia Ortíz",    institution: "Universidad de Santiago de Chile", zone: "usach", category: "researcher" },
  {
    id: "felipe-arenas",
    name: "Dr. Felipe Arenas",
    institution: "Universidad de Santiago de Chile",
    zone: "usach",
    category: "researcher",
    scholarUrl: S("AQ7yOeIAAAAJ"),
    expertise: "Microbiología molecular, biorremediación",
  },
  { id: "alberto-gonzalez",   name: "Dr. Alberto González",  institution: "Universidad de Santiago de Chile", zone: "usach", category: "researcher" },
  { id: "virgilio-gavic",     name: "Virgilio Gavic",        institution: "Universidad de Santiago de Chile", zone: "usach", category: "researcher" },
  {
    id: "rodrigo-contreras",
    name: "Dr. Rodrigo Contreras",
    institution: "Universidad de Santiago de Chile",
    zone: "usach",
    category: "researcher",
    scholarUrl: S("SwISutgAAAAJ"),
    expertise: "Fisiología vegetal antártica",
  },
  {
    id: "carmen-pizarro",
    name: "Dra. Carmen Pizarro",
    institution: "Universidad de Santiago de Chile",
    zone: "usach",
    category: "researcher",
    scholarUrl: S("hKvrk_MAAAAJ"),
  },

  // Universidad de O'Higgins — ohiggins
  {
    id: "humberto-aponte",
    name: "Dr. Humberto Aponte",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("vTVMRqYAAAAJ"),
    expertise: "Ecología de suelos, enzimas del suelo, contaminación",
  },
  {
    id: "morgan-derrien",
    name: "Dra. Morgane Derrien",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("vZE2FMIAAAAJ"),
  },
  {
    id: "claudia-rojas",
    name: "Dra. Claudia Rojas",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("DdmIhqMAAAAJ"),
  },
  {
    id: "manuel-martinez",
    name: "Dr. Manuel Martínez",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("LMTdtVYAAAAJ"),
    expertise: "Microgrids, control de sistemas multi-agente",
  },
  {
    id: "jorge-romero",
    name: "Dr. Jorge Romero",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("hhnmVMUAAAAJ"),
    expertise: "Volcanología, peligros geológicos",
  },
  {
    id: "laura-becerril",
    name: "Dra. Laura Becerril",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("Nd2n2y0AAAAJ"),
    expertise: "Estructura volcánica, peligros volcánicos",
  },
  {
    id: "raul-valenzuela",
    name: "Dr. Raúl Valenzuela",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("7Gxwv5oAAAAJ"),
    expertise: "Precipitación orográfica, ríos atmosféricos",
  },
  {
    id: "etienne-bresciani",
    name: "Dr. Etienne Bresciani",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("TowPuucAAAAJ"),
  },
  {
    id: "alejandro-venegas",
    name: "Dr. Alejandro Venegas",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("vO6QYDgAAAAJ"),
  },
  {
    id: "ernesto-san-blas",
    name: "Dr. Ernesto San Blas",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("jzjK7j0AAAAJ"),
  },
  {
    id: "alexander-vergara",
    name: "Dr. Alexander Vergara",
    institution: "Universidad de O'Higgins",
    zone: "ohiggins",
    category: "researcher",
    scholarUrl: S("AQKvOdQAAAAJ"),
    expertise: "Bioinformática, biología de redes, respuesta al estrés en plantas",
  },
  { id: "wilson-cortes", name: "Wilson Cortés", institution: "Universidad de O'Higgins", zone: "ohiggins", category: "researcher" },

  // Universidad de La Frontera — centro
  {
    id: "marcela-calabi-floody",
    name: "Dra. Marcela Calabi-Floody",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("CmmbHmMAAAAJ"),
    expertise: "Ciencia del suelo, secuestro de carbono, suelos volcánicos, nanotecnología",
  },
  {
    id: "francisco-matus",
    name: "Dr. Francisco Matus",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("h4Tg7eQAAAAJ"),
    expertise: "Materia orgánica del suelo, ciclos biogeoquímicos, dinámica del carbono",
  },
  {
    id: "leon-bravo",
    name: "Dr. León A. Bravo",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("_ERGBOEAAAAJ"),
    expertise: "Ecofisiología vegetal, plantas antárticas, extremófitos",
  },
  {
    id: "maria-mora",
    name: "Dra. María de la Luz Mora",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("dqABFysAAAAJ"),
    expertise: "Microbiología de suelos, rizosfera, suelos volcánicos",
  },
  {
    id: "milko-jorquera",
    name: "Dr. Milko Jorquera",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("mb_L_nwAAAAJ"),
    expertise: "Ecología microbiana, bioprospección de extremófilos",
  },
  {
    id: "cledir-santos",
    name: "Dr. Cledir Santos",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("tG2mCyMAAAAJ"),
    expertise: "Biotecnología fúngica, hongos y cambio climático, resistencia antifúngica",
  },
  {
    id: "marjorie-reyes",
    name: "Dra. Marjorie Reyes-Díaz",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("OjoSgUYAAAAJ"),
    expertise: "Fisiología y bioquímica vegetal, resistencia al estrés hídrico",
  },
  {
    id: "alejandra-ribera",
    name: "Dra. Alejandra Ribera Fonseca",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    expertise: "Nutrición vegetal",
  },
  {
    id: "fernanda-cid",
    name: "Dra. Fernanda Cid Alda",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("HCKbmzMAAAAJ"),
  },
  {
    id: "paula-cartes",
    name: "Dra. Paula Cartes Indo",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    expertise: "Nutrición vegetal",
  },
  {
    id: "claudio-lamilla",
    name: "Dr. Claudio Lamilla",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("-lsH3uUAAAAJ"),
    expertise: "Microbiología",
  },
  {
    id: "patricio-barra",
    name: "Dr. Patricio Barra",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("KQaHpa8AAAAJ"),
    expertise: "Microbiología de suelos",
  },
  {
    id: "cesar-arriagada",
    name: "Dr. César Arriagada Escamilla",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("q6yo0UIAAAAJ"),
    expertise: "Biorremediación, micorrizas",
  },
  {
    id: "patricia-saez",
    name: "Dra. Patricia Sáez Delgado",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("2D9ZitUAAAAJ"),
    expertise: "Ecofisiología vegetal antártica",
  },
  {
    id: "carolina-merino",
    name: "Dra. Carolina Merino",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("fW-3JM0AAAAJ"),
    expertise: "Geomicrobiología, mineralogía",
  },
  {
    id: "mara-cea",
    name: "Dra. Mara Cea",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("QyCzrYcAAAAJ"),
  },
  {
    id: "michel-abanto",
    name: "Dr. Michel Abanto",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("aIZMsJ0AAAAJ"),
  },
  {
    id: "adison-altamirano",
    name: "Dr. Adison Altamirano",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("ilJDLokAAAAJ"),
    expertise: "Ecología del paisaje, incendios forestales, conservación",
  },
  {
    id: "alejandro-miranda",
    name: "Dr. Alejandro Miranda",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("jnCygvAAAAAJ"),
    expertise: "Ecología del paisaje, teledetección, incendios",
  },
  {
    id: "daniel-basualto",
    name: "Dr. Daniel Basualto Alarcón",
    institution: "Universidad de La Frontera",
    zone: "centro",
    category: "researcher",
    scholarUrl: S("IeG8Zo8AAAAJ"),
  },
  { id: "ronald-cancino",    name: "Ronald Cancino Salas",    institution: "Universidad de La Frontera", zone: "centro", category: "researcher", expertise: "Ciencias Sociológicas" },

  // Universidad de Magallanes — sur
  {
    id: "juan-aravena",
    name: "Dr. Juan Carlos Aravena",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("Li7lgskAAAAJ"),
    expertise: "Ecología antártica, glaciología",
  },
  {
    id: "sergio-radic",
    name: "Dr. Sergio Radic",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("fvJOtRIAAAAJ"),
    expertise: "Suelos, pastizales, manejo de praderas",
  },
  {
    id: "elke-schuttler",
    name: "Dra. Elke Schüttler",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("zOYi5KwAAAAJ"),
    expertise: "Conservación, mamíferos, especies invasoras, Programa Subantártico",
  },
  {
    id: "javier-diaz",
    name: "Dr. Javier Díaz",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("XHGCYcsAAAAJ"),
  },
  {
    id: "nelso-navarro",
    name: "Dr. Nelso Navarro",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("CmIXLdMAAAAJ"),
  },
  {
    id: "flavia-morello",
    name: "Dra. Flavia Morello",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("SvAEiwsAAAAJ"),
    expertise: "Arqueología, patrimonio, Instituto de la Patagonia",
  },
  {
    id: "jaime-ojeda",
    name: "Dr. Jaime Ojeda",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("cMgSYGQAAAAJ"),
    expertise: "Socio-ecología marina, etnoecología, conservación",
  },
  {
    id: "jimena-torres",
    name: "Dra. Jimena Torres",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("B5jnLdYAAAAJ"),
  },
  {
    id: "ricardo-rozzi",
    name: "Dr. Ricardo Rozzi",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("b3y2fQUAAAAJ"),
    expertise: "Conservación biocultural, ética ambiental",
  },
  {
    id: "yolanda-espinoza",
    name: "Dra. Yolanda Espinoza",
    institution: "Universidad de Magallanes",
    zone: "sur",
    category: "researcher",
    scholarUrl: S("aMUfA_wAAAAJ"),
  },
  { id: "victor-sierpe",         name: "Víctor Sierpe",              institution: "Universidad de Magallanes", zone: "sur", category: "researcher", expertise: "Arqueología de cazadores-recolectores" },
  { id: "claudia-mansilla",      name: "Dra. Claudia Mansilla",      institution: "Universidad de Magallanes", zone: "sur", category: "researcher", scholarUrl: S("8jkdO00AAAAJ") },
];
