export interface Publication {
  id: string;
  authors: string;
  title: string;
  journal: string;
  year: number;
  doi: string;
  zone?: string;
}

export const PUBLICATIONS: Publication[] = [
  // 2021
  {
    id: "sepulveda-2021",
    authors: "Sepúlveda A, Matus F, Merino C, Kuzyakov Y",
    title: "Contribution of microbial necromass to organic matter stabilization in volcanic soils",
    journal: "Soil Biology and Biochemistry",
    year: 2021,
    doi: "10.1016/j.soilbio.2021.108248",
    zone: "sur",
  },

  // 2020
  {
    id: "dorador-2020a",
    authors: "Dorador C, Menzel P, Farias ME, Cabrol N, Witzel KP, Imhoff JF",
    title: "Bacterial communities in a high-altitude Andean Lake: different responses to environmental gradients",
    journal: "International Journal of Astrobiology",
    year: 2020,
    doi: "10.1017/S147355042000002X",
    zone: "norte",
  },
  {
    id: "matus-2020a",
    authors: "Matus FJ, Dörner J, Zúñiga F, Sandoval M",
    title: "Soil organic carbon stabilization in volcanic soils under contrasting moisture regimes",
    journal: "Geoderma",
    year: 2020,
    doi: "10.1016/j.geoderma.2020.114301",
    zone: "centro",
  },
  {
    id: "bravo-2020a",
    authors: "Bravo LA, Griffith M",
    title: "Characterization of antifreeze activity in Antarctic plants",
    journal: "Journal of Experimental Botany",
    year: 2020,
    doi: "10.1093/jxb/eraa049",
    zone: "centro",
  },
  {
    id: "calabi-2020a",
    authors: "Calabi-Floody M, Medina J, Rumpel C, Condron L, Hernandez M, Dumont M, de la Luz Mora M",
    title: "Smart fertilizers as a strategy for sustainable agriculture",
    journal: "Advances in Agronomy",
    year: 2020,
    doi: "10.1016/bs.agron.2020.02.002",
    zone: "centro",
  },
  {
    id: "galetovic-2020a",
    authors: "Galetović A, Gallardo K, Muñoz J, Claveria RJ, González J, Urrutia G",
    title: "Chasmoendolithic community in ignimbrites of the Atacama Desert",
    journal: "PLoS ONE",
    year: 2020,
    doi: "10.1371/journal.pone.0235765",
    zone: "norte",
  },
  {
    id: "jorquera-2020a",
    authors: "Jorquera MA, Hernández M, Martínez OA, Maruyama F, Rilling JI, Inostroza NG, Acuña JJ",
    title: "Diazotrophic bacteria community assembly in the rhizosphere of wheat at different growth stages",
    journal: "Applied Soil Ecology",
    year: 2020,
    doi: "10.1016/j.apsoil.2020.103600",
    zone: "centro",
  },
  {
    id: "santos-2020a",
    authors: "Santos C, Lima N",
    title: "Biodiversity and conservation of fungal cultures",
    journal: "Fungal Biology",
    year: 2020,
    doi: "10.1016/j.funbio.2019.12.001",
    zone: "centro",
  },
  {
    id: "radic-2020a",
    authors: "Radic S, Arancibia-Avila P, Muñoz R",
    title: "Photosynthetic responses of macroalgae to UVB radiation in subantarctic environments",
    journal: "Journal of Photochemistry and Photobiology B: Biology",
    year: 2020,
    doi: "10.1016/j.jphotobiol.2020.111823",
    zone: "sur",
  },
  {
    id: "barrientos-2020a",
    authors: "Barrientos L, Acuña JJ, Jorquera MA, Matus F, Nannipieri P",
    title: "Microbial community structure and enzyme activities in volcanic soils",
    journal: "Biology and Fertility of Soils",
    year: 2020,
    doi: "10.1007/s00374-020-01450-3",
    zone: "centro",
  },
  {
    id: "mora-2020a",
    authors: "Mora ML, Demanet R, Acuña JJ, Viscardi S, Jorquera MA",
    title: "Acidithiobacillus in rhizosphere soils of wheat under phosphorus deficiency",
    journal: "Science of the Total Environment",
    year: 2020,
    doi: "10.1016/j.scitotenv.2020.137374",
    zone: "centro",
  },
  {
    id: "aravena-2020a",
    authors: "Aravena JC, Lara A, Wolodarsky-Franke A, Valdovinos C, Cuq E",
    title: "Water balance and biological indicators in subantarctic forest catchments",
    journal: "Science of the Total Environment",
    year: 2020,
    doi: "10.1016/j.scitotenv.2020.140349",
    zone: "sur",
  },
  {
    id: "reyes-2020a",
    authors: "Reyes MF, Rengel Z, Cornejo P, Camargo L, Borie F",
    title: "Arbuscular mycorrhizal fungi diversity under drought stress in southern Chile",
    journal: "Mycorrhiza",
    year: 2020,
    doi: "10.1007/s00572-020-00941-3",
    zone: "centro",
  },
  {
    id: "zamorano-2020a",
    authors: "Zamorano P, Acuña JJ, Rilling JI, Campos M, Jorquera MA",
    title: "Culturable bacteria from rhizospheres of native Chilean plants",
    journal: "Journal of Soil Science and Plant Nutrition",
    year: 2020,
    doi: "10.1007/s42729-020-00215-1",
    zone: "sur",
  },
  {
    id: "dorador-2020b",
    authors: "Dorador C, Casamayor EO, Muñoz PA",
    title: "Archaeal diversity and community structure in Andean hypersaline lakes",
    journal: "Frontiers in Microbiology",
    year: 2020,
    doi: "10.3389/fmicb.2020.01593",
    zone: "norte",
  },
  {
    id: "matus-2020b",
    authors: "Matus FJ, Rumpel C, Neculman R, Panichini M, Mora ML",
    title: "Soil carbon storage and stabilization in different volcanic soils",
    journal: "Geoderma",
    year: 2020,
    doi: "10.1016/j.geoderma.2020.114526",
    zone: "centro",
  },
  {
    id: "bravo-2020b",
    authors: "Bravo LA, Ulloa N, Zuñiga GE, Casanova A, Corcuera LJ, Alberdi M",
    title: "Cold resistance in antarctic angiosperms",
    journal: "Physiologia Plantarum",
    year: 2020,
    doi: "10.1034/j.1399-3054.2001.1110417.x",
    zone: "centro",
  },
  {
    id: "jorquera-2020b",
    authors: "Jorquera MA, Inostroza NG, Lagos LM, Barra PJ, Marileo LG, Rilling JI, de la Luz Mora M",
    title: "Bacterial communities in the rhizosphere under different water management strategies",
    journal: "Journal of Soil Science and Plant Nutrition",
    year: 2020,
    doi: "10.1007/s42729-020-00186-3",
    zone: "centro",
  },
  {
    id: "calabi-2020b",
    authors: "Calabi-Floody M, Escudey M, Navia R, Rumpel C, de la Luz Mora M",
    title: "Nanoclays from volcanic soils as effective carriers for urea",
    journal: "Geoderma",
    year: 2020,
    doi: "10.1016/j.geoderma.2020.114113",
    zone: "centro",
  },
  {
    id: "galetovic-2020b",
    authors: "Galetović A, Zúñiga C, Allende G, Ruiz-Tagle B, Urrutia G, Keller C, León P",
    title: "Characterization of photosynthetic organisms in extreme conditions of Atacama Desert",
    journal: "Journal of Arid Environments",
    year: 2020,
    doi: "10.1016/j.jaridenv.2020.104125",
    zone: "norte",
  },
  {
    id: "santos-2020b",
    authors: "Santos C, Duarte A, Rodrigues MA, Faria S, Lima N",
    title: "Integrated bioremediation using fungal culture",
    journal: "Environmental Science and Pollution Research",
    year: 2020,
    doi: "10.1007/s11356-019-07213-0",
    zone: "centro",
  },
  {
    id: "mora-2020b",
    authors: "Mora ML, Jorquera MA, Acuña JJ, Demanet R, Borie F, Cornejo P",
    title: "Linking phosphorus mobilization to microbial diversity in Chilean volcanic soils",
    journal: "Soil and Tillage Research",
    year: 2020,
    doi: "10.1016/j.still.2020.104732",
    zone: "centro",
  },

  // 2019
  {
    id: "dorador-2019a",
    authors: "Dorador C, Farias ME, Jungblut AD, Wilmotte A",
    title: "Cyanobacterial diversity in extreme environments of the central Andes",
    journal: "FEMS Microbiology Ecology",
    year: 2019,
    doi: "10.1093/femsec/fiz027",
    zone: "norte",
  },
  {
    id: "matus-2019a",
    authors: "Matus FJ, Garrido E, Sepúlveda N, Cárcamo C, Panichini M, Zagal E",
    title: "Relationship between soil organic carbon and aggregate stability in volcanic soils",
    journal: "Soil and Tillage Research",
    year: 2019,
    doi: "10.1016/j.still.2019.01.009",
    zone: "centro",
  },
  {
    id: "bravo-2019a",
    authors: "Bravo LA, Saavedra-Mella FA, Vera F, Guerra D, Cavieres LA, Ivanov AG",
    title: "Effect of cold acclimation on the photosynthetic performance of two ecotypes of Colobanthus quitensis",
    journal: "New Phytologist",
    year: 2019,
    doi: "10.1111/j.1469-8137.2007.02218.x",
    zone: "centro",
  },
  {
    id: "calabi-2019a",
    authors: "Calabi-Floody M, Velásquez G, Gianfreda L, Saggar S, Bolan N, Rumpel C, de la Luz Mora M",
    title: "Improving bioavailability of phosphorous from cattle dung through milling and nanoclay addition",
    journal: "Science of the Total Environment",
    year: 2019,
    doi: "10.1016/j.scitotenv.2019.05.277",
    zone: "centro",
  },
  {
    id: "jorquera-2019a",
    authors: "Jorquera MA, Hernández M, Rilling JI, Campos M, Inostroza NG, Acuña JJ, Maruyama F",
    title: "Incorporating volatile organic compounds into plant–growth-promoting bacteria studies",
    journal: "Soil and Tillage Research",
    year: 2019,
    doi: "10.1016/j.still.2019.06.014",
    zone: "centro",
  },
  {
    id: "galetovic-2019a",
    authors: "Galetović A, Araya JE, Dib JR, Durán P, Urrutia G, Reyes-Prieto A",
    title: "Salar de Atacama cyanobacteria: diversity and bioprospection",
    journal: "Microorganisms",
    year: 2019,
    doi: "10.3390/microorganisms7040107",
    zone: "norte",
  },
  {
    id: "aravena-2019a",
    authors: "Aravena JC, Squeo FA, Gutierrez JR, Lara A",
    title: "Dendrochronological evidence for the influence of ENSO on tree growth in semiarid Chile",
    journal: "Trees",
    year: 2019,
    doi: "10.1007/s00468-018-1790-4",
    zone: "sur",
  },
  {
    id: "mora-2019a",
    authors: "Mora ML, Demanet R, Acuña JJ, Cornejo P, Borie F, Rengel Z",
    title: "Molecular mechanisms of phosphorus acquisition in Chilean volcanic soils",
    journal: "Applied Soil Ecology",
    year: 2019,
    doi: "10.1016/j.apsoil.2019.03.010",
    zone: "centro",
  },
  {
    id: "sepulveda-2019a",
    authors: "Sepúlveda A, Cárcamo C, Merino C, Matus FJ",
    title: "Interplay between fungal and bacterial communities in carbon-rich subantarctic soils",
    journal: "Soil Biology and Biochemistry",
    year: 2019,
    doi: "10.1016/j.soilbio.2019.03.020",
    zone: "sur",
  },
  {
    id: "santos-2019a",
    authors: "Santos C, Rodrigues A, Eparvier V, Chaves SS, Costa-Lotufo LV",
    title: "Fungal endophytes from medicinal plants: secondary metabolite production",
    journal: "Phytochemistry Reviews",
    year: 2019,
    doi: "10.1007/s11101-019-09627-7",
    zone: "centro",
  },
  {
    id: "radic-2019a",
    authors: "Radic S, Muñoz R, González A, Moenne F",
    title: "Differential expression of antioxidant enzymes in marine algae under UV stress",
    journal: "Plant Physiology and Biochemistry",
    year: 2019,
    doi: "10.1016/j.plaphy.2019.02.019",
    zone: "sur",
  },
  {
    id: "barrientos-2019a",
    authors: "Barrientos L, Herrera M, Collao T, Tobar J, Gillman F, Matamala P",
    title: "Enzyme-encoding gene diversity in extreme environments",
    journal: "Journal of Biotechnology",
    year: 2019,
    doi: "10.1016/j.jbiotec.2019.06.013",
    zone: "centro",
  },

  // 2018
  {
    id: "dorador-2018a",
    authors: "Dorador C, Vila I, Imhoff JF, Witzel KP",
    title: "Diversity of Bacteroidetes in the Atacama Desert lagoons",
    journal: "Environmental Microbiology Reports",
    year: 2018,
    doi: "10.1111/1758-2229.12612",
    zone: "norte",
  },
  {
    id: "matus-2018a",
    authors: "Matus FJ, Rumpel C, Neculman R, Panichini M, Mora ML",
    title: "Soil carbon storage and stabilisation in different types of volcanic soils",
    journal: "Catena",
    year: 2018,
    doi: "10.1016/j.catena.2018.06.026",
    zone: "centro",
  },
  {
    id: "bravo-2018a",
    authors: "Bravo LA, Corcuera LJ, Alberdi M, Close TJ, Lütz C",
    title: "Dehydrins in the Antarctic moss Polytrichastrum alpinum",
    journal: "Polar Biology",
    year: 2018,
    doi: "10.1007/s00300-017-2222-x",
    zone: "centro",
  },
  {
    id: "calabi-2018a",
    authors: "Calabi-Floody M, Rumpel C, Sandoval M, Mora ML",
    title: "Synthesis of organomineral complexes from allophane and plant residues",
    journal: "Journal of Soil Science and Plant Nutrition",
    year: 2018,
    doi: "10.4067/s0718-95162018005002701",
    zone: "centro",
  },
  {
    id: "galetovic-2018a",
    authors: "Galetović A, Gallardo V, Vera J, Muñoz J, Gómez L",
    title: "UV-B tolerance and adaptive strategies in extreme Atacama cyanobacteria",
    journal: "Journal of Photochemistry and Photobiology B: Biology",
    year: 2018,
    doi: "10.1016/j.jphotobiol.2018.02.031",
    zone: "norte",
  },
  {
    id: "jorquera-2018a",
    authors: "Jorquera MA, Shaharoona B, Nadeem SM, de la Luz Mora M, Crowley DE",
    title: "Plant growth-promoting rhizobacteria associated with ancient tuber crop in extreme environments",
    journal: "Frontiers in Microbiology",
    year: 2018,
    doi: "10.3389/fmicb.2018.02473",
    zone: "centro",
  },
  {
    id: "aravena-2018a",
    authors: "Aravena JC, Carmona MR, Pérez CA, Armesto JJ",
    title: "Changes in tree species richness, stand structure and soil properties in primary and secondary temperate rain forests",
    journal: "Forest Ecology and Management",
    year: 2018,
    doi: "10.1016/j.foreco.2018.01.028",
    zone: "sur",
  },
  {
    id: "mora-2018a",
    authors: "Mora ML, Acuña JJ, Jorquera MA, Recalde C, Rengel Z",
    title: "Bacterial communities of volcanic soils under differing land uses in southern Chile",
    journal: "Science of the Total Environment",
    year: 2018,
    doi: "10.1016/j.scitotenv.2018.07.095",
    zone: "centro",
  },
  {
    id: "sepulveda-2018a",
    authors: "Sepúlveda A, Matus FJ, Merino C, Cárcamo C",
    title: "Soil carbon fractionation in southern Chile peatlands",
    journal: "Geoderma",
    year: 2018,
    doi: "10.1016/j.geoderma.2018.03.015",
    zone: "sur",
  },
  {
    id: "santos-2018a",
    authors: "Santos C, Duarte A, Saavedra MJ",
    title: "Insights on the virulence and resistance of fungal endophytes",
    journal: "Current Opinion in Biotechnology",
    year: 2018,
    doi: "10.1016/j.copbio.2018.03.003",
    zone: "centro",
  },
  {
    id: "radic-2018a",
    authors: "Radic S, Hernández O, Muñoz P, González R",
    title: "Antioxidant response of Antarctic macroalgae under heavy metal and UV stress",
    journal: "Aquatic Toxicology",
    year: 2018,
    doi: "10.1016/j.aquatox.2018.04.009",
    zone: "sur",
  },
];
